In [3]:
from pathlib import Path
import os
import sys

import pandas as pd

cwd = Path.cwd().resolve()
if (cwd / "src").exists():
    PROJECT_ROOT = cwd
elif (cwd.parent / "src").exists():
    PROJECT_ROOT = cwd.parent
else:
    raise RuntimeError("Could not infer project root from notebook location.")

os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 220)

print(f"Project root: {PROJECT_ROOT}")

Project root: /mnt/c/Research/LLMAgora

In [4]:
from dataclasses import fields

from agora.eval_aggregate import build_experiment_analysis_dataframe
from agora.experiment import ExperimentConfig, SEMANTIC_ANALYSIS_METRICS, SEMANTIC_SIMILARITY_METHOD_COSINE
from agora.semantic_similarity_analyzer import DEFAULT_COSINE_MODEL_NAME, DEFAULT_NLI_MODEL_NAME
from agora.persona_adherence_evaluator import (
    PERSONA_METRIC_PRIVATE_PER_TURN,
    PERSONA_METRIC_PUBLIC_PER_TURN,
)
from agora.emotion_analyzer import DEFAULT_EMOTION_MODEL

EXPERIMENT_CONFIG_FIELDS = {field.name for field in fields(ExperimentConfig)}
LLM_JUDGE_METRICS = [
    PERSONA_METRIC_PUBLIC_PER_TURN,
    PERSONA_METRIC_PRIVATE_PER_TURN,
]

MANIFEST_PATH = PROJECT_ROOT / "outputs" / "sweeps_9" / "manifest.json"
SWEEP_ROOT = MANIFEST_PATH.parent

postpro = {
    "device": "cuda",
    "no_stance_only": False,
    "enable_nli": True,
    "nli_model_name": DEFAULT_NLI_MODEL_NAME,
    "enable_emotions": True,
    "emotion_model_name": DEFAULT_EMOTION_MODEL,
    "enable_llm_judge": True,
    "semantic_similarity_method": SEMANTIC_SIMILARITY_METHOD_COSINE,
    "semantic_similarity_model": DEFAULT_COSINE_MODEL_NAME,
    "persona_scoring_model": "anthropic/claude-sonnet-4.6",
    "persona_score_samples": 3,
}

postpro["semantic_analysis_metrics"] = list(SEMANTIC_ANALYSIS_METRICS)
postpro["semantic_similarity_device"] = postpro["device"]
postpro["persona_analysis_metrics"] = (
    list(LLM_JUDGE_METRICS) if postpro["enable_llm_judge"] else []
)

analysis_kwargs = {
    key: value for key, value in postpro.items() if key in EXPERIMENT_CONFIG_FIELDS
}
analysis_kwargs["catalog_path"] = str(PROJECT_ROOT / "data" / "scenarios.json")
analysis_kwargs["prompts_path"] = str(PROJECT_ROOT / "data" / "prompts.json")

analysis_kwargs

{'semantic_similarity_method': 'cosine',
 'semantic_similarity_model': 'all-mpnet-base-v2',
 'persona_scoring_model': 'anthropic/claude-sonnet-4.6',
 'persona_score_samples': 3,
 'semantic_analysis_metrics': ['self_consistency',
  'cross_agent_public_alignment',
  'cross_agent_private_alignment'],
 'semantic_similarity_device': 'cuda',
 'persona_analysis_metrics': ['public_per_turn', 'private_per_turn'],
 'catalog_path': '/mnt/c/Research/LLMAgora/data/scenarios.json',
 'prompts_path': '/mnt/c/Research/LLMAgora/data/prompts.json'}

In [5]:
import time

start_time = time.time()

aggregate_df = build_experiment_analysis_dataframe(
    MANIFEST_PATH,
    analysis_kwargs=analysis_kwargs,
    include_nli=postpro["enable_nli"],
    nli_model_name=postpro["nli_model_name"],
    include_emotions=postpro["enable_emotions"],
    emotion_model_name=postpro["emotion_model_name"],
    device=postpro["device"],
    no_stance_only=postpro["no_stance_only"],
)

end_time = time.time()

print(f"Rows: {len(aggregate_df)}")
display(
    aggregate_df[
        [
            "experiment_index",
            "model",
            "incentive_type",
            "incentive_direction",
            "scenario_id",
            "repeat_count",
        ]
    ].head()
)

elapsed_time = end_time - start_time
hours = int(elapsed_time // 3600)
minutes = int((elapsed_time % 3600) // 60)
seconds = int(elapsed_time % 60)

print(f"Time taken: {hours} hr {minutes} min {seconds} sec")
print("No-stance columns:")
for col in aggregate_df.columns:
    if col.endswith("no_stance"):
        print(f"- {col}")

/home/snoroozi/anaconda3/envs/agora_eval/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

The `reference_compile` argument is deprecated and will be removed in `transformers v5.2.0`Use `torch.compile()` directly on the model instead.

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading cosine model: all-mpnet-base-v2...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading nli model: dleemiller/finecat-nli-l...

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading emotion model: cirimus/modernbert-base-emotions...

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Rows: 60

   experiment_index           model incentive_type incentive_direction                    scenario_id  repeat_count
0                 0  openai/gpt-5.4     historical            negative            promotion_committee             5
1                 1  openai/gpt-5.4     historical            negative        ngo_climate_endorsement             5
2                 2  openai/gpt-5.4     historical            negative  faculty_manuscript_submission             5
3                 3  openai/gpt-5.4         future            negative            promotion_committee             5
4                 4  openai/gpt-5.4         future            negative        ngo_climate_endorsement             5

Time taken: 6 hr 28 min 49 sec
No-stance columns:
- cosine-similarity-self-consistency-no_stance
- cosine-similarity-cross-agent-alignment-no_stance
- cosine-similarity-self-consistency-all-repeats-no_stance
- cosine-similarity-cross-agent-alignment-all-repeats-no_stance
- nli-self-consistency-no_stance
- nli-cross-agent-alignment-no_stance
- nli-self-consistency-all-repeats-no_stance
- nli-cross-agent-alignment-all-repeats-no_stance

In [6]:
# Save aggregate_df to pickle.
import pickle

output_path = SWEEP_ROOT / "aggregate_df_big_mac_plus.pkl"
with open(output_path, "wb") as f:
    pickle.dump(aggregate_df, f)

print(f"Saved: {output_path}")

Saved: /mnt/c/Research/LLMAgora/outputs/sweeps_9/aggregate_df_big_mac_plus.pkl

In [ ]:
aggregate_df
# positive future 6
# positive historical 7
# none 8
# future historical negative 9

,experiment_index,config_fingerprint,repeat_count,case_ids,model,incentive_direction,incentive_type,scenario_id,cosine-similarity-self-consistency,cosine-similarity-cross-agent-alignment,cosine-similarity-self-consistency-all-repeats,cosine-similarity-cross-agent-alignment-all-repeats,persona-individual-turn-scores,persona-cumulative-scores,persona-full-debate-scores,persona-individual-turn-scores-all-repeats,persona-cumulative-scores-all-repeats,persona-full-debate-scores-all-repeats,survey-public,survey-private,survey-diff-public-minus-private,survey-public-all-repeats,survey-private-all-repeats,survey-diff-public-minus-private-all-repeats,decision-self-consistency,decision-cross-agent-alignment,decision-self-consistency-all-repeats,decision-cross-agent-alignment-all-repeats,cosine-similarity-self-consistency-no_stance,cosine-similarity-cross-agent-alignment-no_stance,cosine-similarity-self-consistency-all-repeats-no_stance,cosine-similarity-cross-agent-alignment-all-repeats-no_stance,nli-self-consistency,nli-cross-agent-alignment,nli-self-consistency-all-repeats,nli-cross-agent-alignment-all-repeats,nli-self-consistency-no_stance,nli-cross-agent-alignment-no_stance,nli-self-consistency-all-repeats-no_stance,nli-cross-agent-alignment-all-repeats-no_stance,emotion-public-utterances,emotion-private-reflections,emotion-public-utterances-all-repeats,emotion-private-reflections-all-repeats
0,0,fd45ab5b8d95d689e5b45b28d60666de5ce1923f871964...,5,"[884a7f33618a, 063a783aeee0, 5781e1b57304, eb1...",openai/gpt-5.4,negative,historical,promotion_committee,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'PROMOTE', 'channel_tuple_orderin...","{'decision': 'PROMOTE', 'agent_tuple_ordering'...","{'decision': 'PROMOTE', 'channel_tuple_orderin...","{'decision': 'PROMOTE', 'agent_tuple_ordering'...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
1,1,f55bea02cdadf9e9382100f827a7d13d75d2f612474c86...,5,"[a898f3f0b1c6, d44543292225, 6e940780ceae, dcd...",openai/gpt-5.4,negative,historical,ngo_climate_endorsement,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'ENDORSE', 'channel_tuple_orderin...","{'decision': 'ENDORSE', 'agent_tuple_ordering'...","{'decision': 'ENDORSE', 'channel_tuple_orderin...","{'decision': 'ENDORSE', 'agent_tuple_ordering'...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
2,2,8cdd0142976ecab98b0221d85e13e0166fdf003525e6ce...,5,"[c9b5be0e88b0, d753b5235e68, b519cda668b2, 7f3...",openai/gpt-5.4,negative,historical,faculty_manuscript_submission,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'SUBMIT NOW', 'channel_tuple_orde...","{'decision': 'SUBMIT NOW', 'agent_tuple_orderi...","{'decision': 'SUBMIT NOW', 'channel_tuple_orde...","{'decision': 'SUBMIT NOW', 'agent_tuple_orderi...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
3,3,bc15359ff6dfd44c9d41bf15013a2288a9e05d4bc13960...,5,"[a8926bd4eaf5, e55e2e56cc14, de0784c978d7, 71e...",openai/gpt-5.4,negative,future,promotion_committee,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'PROMOTE', 'channel_tuple_orderin...","{'decision': 'PROMOTE', 'agent_tuple_ordering'...","{'decision': 'PROMOTE', 'channel_tuple_orderin...","{'decision': 'PROMOTE', 'agent_tuple_ordering'...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
4,4,bb3e343479b307bd5f721ad5fc2ab2ff45b098da36c2ce...,5,"[2343e1685c25, 028df5261eb9, 939d77e6ac05, 008...",openai/gpt-5.4,negative,future,ngo_climate_endorsement,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'ENDORSE', 'channel_tuple_orderin...","{'decision': 'ENDORSE', 'agent_tuple_ordering'...","{'decision': 'ENDORSE', 'channel_tuple_orderin...","{'decision': 'ENDORSE', 'agent_tuple_ordering'...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
5,5,d4e9c6fd4901a7dc08afe47f24b4912afa057e3aac4cf8...,5,"[9a3f2ee1df02, c45558746f1f, 40e81b70dfca, 351...",openai/gpt-5.4,negative,future,faculty_manuscript_submission,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'SUBMIT NOW', 'channel_tuple_orde...","{'decision': 'SUBMIT NOW', 'agent_tuple_orderi...","{'decision': 'SUBMIT NOW', 'channel_tuple_orde...","{'decision': 'SUBMIT NOW', 'agent_tuple_orderi...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
6,6,abb06d37ef0e9f41d97377f8ce23cda3de9e7191bde5c4...,5,"[5a417e788f6d, f12f2d24c166, bafe22641840, 2b0...",openai/gpt-oss-120b,negative,historical,promotion_committee,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'PROMOTE', 'channel_tuple_orderin...","{'decision': 'PROMOTE', 'agent_tuple_ordering'...","{'decision': 'PROMOTE', 'channel_tuple_orderin...","{'decision': 'PROMOTE', 'agent_tuple_ordering'...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
7,7,3844ace16d47b3b16298030d939b2c4d92f3e4a891a57d...,5,"[d77255a802e5, 6edcb8a900f7, b1861416b0c9, 3e1...",openai/gpt-oss-120b,negative,historical,ngo_climate_endorsement,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'ENDORSE', 'channel_tuple_orderin...","{'decision': 'ENDORSE', 'agent_tuple_ordering'...","{'decision': 'ENDORSE', 'channel_tuple_orderin...","{'decision': 'ENDORSE', 'agent_tuple_ordering'...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."
8,8,fd85050ed818c8130219247f6bd39dcb27e6f95b0585c2...,5,"[ec4ff1615a4d, 8433ea387841, 048802b8609f, 912...",openai/gpt-oss-120b,negative,historical,faculty_manuscript_submission,"{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'public': {'debate_turn': [1, 2, 3,...","{'alpha': {'public': {'debate_turn': [], 'pers...","{'alpha': {'public': {'score': None, 'standard...",{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'debate_tur...,{'repeats': [{'alpha': {'public': {'score': No...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'Q1': {'question': 'I agree with the other pa...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,{'repeats': [{'Q1': {'question': 'I agree with...,"{'decision': 'SUBMIT NOW', 'channel_tuple_orde...","{'decision': 'SUBMIT NOW', 'agent_tuple_orderi...","{'decision': 'SUBMIT NOW', 'channel_tuple_orde...","{'decision': 'SUBMIT NOW', 'agent_tuple_orderi...","{'alpha': {'debate_turn': [1, 2, 3, 4, 5], 'co...","{'public alignment': {'debate_turn': [1, 2, 3,...","{'repeats': [{'alpha': {'debate_turn': [1, 2, ...",{'repeats': [{'public alignment': {'debate_tur...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'n...","{'public utterances': {'debate_turns': [1, 2, ...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...",{'repeats': [{'public utterances': {'debate_tu...,"{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'alpha': {'debate_turns': [1, 2, 3, 4, 5], 'e...","{'repeats': [{'alpha': {'debate_turns': [1, 2,...","{'repeats': [{'alpha': {'debate_turns': [1, 2,..."

In [15]:
import pandas as pd
import numpy as np

has_nan_anywhere = any(
    contains_nan(x)
    for row in aggregate_df.itertuples(index=False)
    for x in row
)
print(f"NaN anywhere: {has_nan_anywhere}")

def contains_nan(x):
    # Dict: recurse into values
    if isinstance(x, dict):
        return any(contains_nan(v) for v in x.values())

    # List / tuple / set: recurse
    if isinstance(x, (list, tuple, set)):
        return any(contains_nan(v) for v in x)

    # Numpy array: handle explicitly
    if isinstance(x, np.ndarray):
        return np.isnan(x).any()

    # Scalar case (safe)
    try:
        return pd.isna(x)
    except Exception:
        return False

found = False

for i, row in enumerate(aggregate_df.itertuples(index=False)):
    for j, x in enumerate(row):
        if contains_nan(x):
            print(f"NaN found at row {i}, column '{aggregate_df.columns[j]}'")
            found = True

if not found:
    print("No NaNs found")

NaN anywhere: True
NaN found at row 0, column 'persona-full-debate-scores'
NaN found at row 0, column 'persona-full-debate-scores-all-repeats'
NaN found at row 1, column 'persona-full-debate-scores'
NaN found at row 1, column 'persona-full-debate-scores-all-repeats'
NaN found at row 2, column 'persona-full-debate-scores'
NaN found at row 2, column 'persona-full-debate-scores-all-repeats'
NaN found at row 3, column 'persona-full-debate-scores'
NaN found at row 3, column 'persona-full-debate-scores-all-repeats'
NaN found at row 4, column 'persona-full-debate-scores'
NaN found at row 4, column 'persona-full-debate-scores-all-repeats'
NaN found at row 5, column 'persona-full-debate-scores'
NaN found at row 5, column 'persona-full-debate-scores-all-repeats'
NaN found at row 6, column 'persona-full-debate-scores'
NaN found at row 6, column 'persona-full-debate-scores-all-repeats'
NaN found at row 7, column 'persona-full-debate-scores'
NaN found at row 7, column 'persona-full-debate-scores-all-repeats'
NaN found at row 8, column 'persona-full-debate-scores'
NaN found at row 8, column 'persona-full-debate-scores-all-repeats'
NaN found at row 9, column 'persona-full-debate-scores'
NaN found at row 9, column 'persona-full-debate-scores-all-repeats'
NaN found at row 10, column 'persona-full-debate-scores'
NaN found at row 10, column 'persona-full-debate-scores-all-repeats'
NaN found at row 11, column 'persona-full-debate-scores'
NaN found at row 11, column 'persona-full-debate-scores-all-repeats'
NaN found at row 12, column 'persona-full-debate-scores'
NaN found at row 12, column 'persona-full-debate-scores-all-repeats'
NaN found at row 13, column 'persona-full-debate-scores'
NaN found at row 13, column 'persona-full-debate-scores-all-repeats'
NaN found at row 14, column 'persona-full-debate-scores'
NaN found at row 14, column 'persona-full-debate-scores-all-repeats'
NaN found at row 15, column 'persona-full-debate-scores'
NaN found at row 15, column 'persona-full-debate-scores-all-repeats'
NaN found at row 16, column 'persona-full-debate-scores'
NaN found at row 16, column 'persona-full-debate-scores-all-repeats'
NaN found at row 17, column 'persona-full-debate-scores'
NaN found at row 17, column 'persona-full-debate-scores-all-repeats'
NaN found at row 18, column 'persona-full-debate-scores'
NaN found at row 18, column 'persona-full-debate-scores-all-repeats'
NaN found at row 19, column 'persona-full-debate-scores'
NaN found at row 19, column 'persona-full-debate-scores-all-repeats'
NaN found at row 20, column 'persona-full-debate-scores'
NaN found at row 20, column 'persona-full-debate-scores-all-repeats'
NaN found at row 21, column 'persona-full-debate-scores'
NaN found at row 21, column 'persona-full-debate-scores-all-repeats'
NaN found at row 22, column 'persona-full-debate-scores'
NaN found at row 22, column 'persona-full-debate-scores-all-repeats'
NaN found at row 23, column 'persona-full-debate-scores'
NaN found at row 23, column 'persona-full-debate-scores-all-repeats'
NaN found at row 24, column 'persona-full-debate-scores'
NaN found at row 24, column 'persona-full-debate-scores-all-repeats'
NaN found at row 25, column 'persona-full-debate-scores'
NaN found at row 25, column 'persona-full-debate-scores-all-repeats'
NaN found at row 26, column 'persona-full-debate-scores'
NaN found at row 26, column 'persona-full-debate-scores-all-repeats'
NaN found at row 27, column 'persona-full-debate-scores'
NaN found at row 27, column 'persona-full-debate-scores-all-repeats'
NaN found at row 28, column 'persona-full-debate-scores'
NaN found at row 28, column 'persona-full-debate-scores-all-repeats'
NaN found at row 29, column 'persona-full-debate-scores'
NaN found at row 29, column 'persona-full-debate-scores-all-repeats'
NaN found at row 30, column 'persona-full-debate-scores'
NaN found at row 30, column 'persona-full-debate-scores-all-repeats'
NaN found at row 31, column 'persona-full-debate-scores'
NaN found at row 31, column 'persona-full-debate-scores-all-repeats'
NaN found at row 32, column 'persona-full-debate-scores'
NaN found at row 32, column 'persona-full-debate-scores-all-repeats'
NaN found at row 33, column 'persona-full-debate-scores'
NaN found at row 33, column 'persona-full-debate-scores-all-repeats'
NaN found at row 34, column 'persona-full-debate-scores'
NaN found at row 34, column 'persona-full-debate-scores-all-repeats'
NaN found at row 35, column 'persona-full-debate-scores'
NaN found at row 35, column 'persona-full-debate-scores-all-repeats'
NaN found at row 36, column 'persona-full-debate-scores'
NaN found at row 36, column 'persona-full-debate-scores-all-repeats'
NaN found at row 37, column 'persona-full-debate-scores'
NaN found at row 37, column 'persona-full-debate-scores-all-repeats'
NaN found at row 38, column 'persona-full-debate-scores'
NaN found at row 38, column 'persona-full-debate-scores-all-repeats'
NaN found at row 39, column 'persona-full-debate-scores'
NaN found at row 39, column 'persona-full-debate-scores-all-repeats'
NaN found at row 40, column 'persona-full-debate-scores'
NaN found at row 40, column 'persona-full-debate-scores-all-repeats'
NaN found at row 41, column 'persona-full-debate-scores'
NaN found at row 41, column 'persona-full-debate-scores-all-repeats'
NaN found at row 42, column 'persona-full-debate-scores'
NaN found at row 42, column 'persona-full-debate-scores-all-repeats'
NaN found at row 43, column 'persona-full-debate-scores'
NaN found at row 43, column 'persona-full-debate-scores-all-repeats'
NaN found at row 44, column 'persona-full-debate-scores'
NaN found at row 44, column 'persona-full-debate-scores-all-repeats'
NaN found at row 45, column 'persona-full-debate-scores'
NaN found at row 45, column 'persona-full-debate-scores-all-repeats'
NaN found at row 46, column 'persona-full-debate-scores'
NaN found at row 46, column 'persona-full-debate-scores-all-repeats'
NaN found at row 47, column 'persona-full-debate-scores'
NaN found at row 47, column 'persona-full-debate-scores-all-repeats'
NaN found at row 48, column 'persona-full-debate-scores'
NaN found at row 48, column 'persona-full-debate-scores-all-repeats'
NaN found at row 49, column 'persona-full-debate-scores'
NaN found at row 49, column 'persona-full-debate-scores-all-repeats'
NaN found at row 50, column 'persona-full-debate-scores'
NaN found at row 50, column 'persona-full-debate-scores-all-repeats'
NaN found at row 51, column 'persona-full-debate-scores'
NaN found at row 51, column 'persona-full-debate-scores-all-repeats'
NaN found at row 52, column 'persona-full-debate-scores'
NaN found at row 52, column 'persona-full-debate-scores-all-repeats'
NaN found at row 53, column 'persona-full-debate-scores'
NaN found at row 53, column 'persona-full-debate-scores-all-repeats'
NaN found at row 54, column 'persona-full-debate-scores'
NaN found at row 54, column 'persona-full-debate-scores-all-repeats'
NaN found at row 55, column 'persona-full-debate-scores'
NaN found at row 55, column 'persona-full-debate-scores-all-repeats'
NaN found at row 56, column 'persona-full-debate-scores'
NaN found at row 56, column 'persona-full-debate-scores-all-repeats'
NaN found at row 57, column 'persona-full-debate-scores'
NaN found at row 57, column 'persona-full-debate-scores-all-repeats'
NaN found at row 58, column 'persona-full-debate-scores'
NaN found at row 58, column 'persona-full-debate-scores-all-repeats'
NaN found at row 59, column 'persona-full-debate-scores'
NaN found at row 59, column 'persona-full-debate-scores-all-repeats'

In [ ]:
# import pickle

# # Load aggregate_df from pickle.
# # input_path = "/mnt/c/Research/LLMAgora/outputs/sweeps_7-1/aggregate_df_no_stance_only.pkl"
# input_path = "/mnt/c/Research/LLMAgora/outputs/sweeps_7/aggregate_df_no_stance_only.pkl"
# with open(input_path, "rb") as f:
#     aggregate_df_sweep_7 = pickle.load(f)

In [11]:
# # positive future 6
# # positive historical 7
# # none 8
# # future historical negative 9

# aggregate_df_sweep_7

In [19]:
import pandas as pd
import numpy as np

has_nan_anywhere = any(
    contains_nan(x)
    for row in aggregate_df_sweep_7.itertuples(index=False)
    for x in row
)
print(f"NaN anywhere: {has_nan_anywhere}")

def contains_nan(x):
    # Explicit None check
    if x is None:
        return True

    # Dict: recurse into values
    if isinstance(x, dict):
        return any(contains_nan(v) for v in x.values())

    # List / tuple / set: recurse
    if isinstance(x, (list, tuple, set)):
        return any(contains_nan(v) for v in x)

    # Numpy array: handle properly (including object dtype)
    if isinstance(x, np.ndarray):
        if x.dtype == object:
            return any(contains_nan(v) for v in x)
        return np.isnan(x).any()

    # Scalar case
    try:
        return pd.isna(x)
    except Exception:
        return False

found = False

for i, row in enumerate(aggregate_df_sweep_7.itertuples(index=False)):
    for j, x in enumerate(row):
        if contains_nan(x):
            print(f"NaN found at row {i}, column '{aggregate_df_sweep_7.columns[j]}'")
            found = True

if not found:
    print("No NaNs found")

NaN anywhere: False
No NaNs found

In [ ]:
experiment_index = 0
row = aggregate_df.loc[aggregate_df["experiment_index"] == experiment_index].iloc[0]

print("Available aggregate columns:")
for col in aggregate_df.columns:
    print(f"- {col}")

row["cosine-similarity-self-consistency-no_stance"]

In [ ]:
row["nli-self-consistency-no_stance"] if "nli-self-consistency-no_stance" in aggregate_df.columns else None

In [ ]:
row["cosine-similarity-cross-agent-alignment-all-repeats-no_stance"]["repeats"][0]

In [ ]:
row["nli-cross-agent-alignment-all-repeats-no_stance"]["repeats"][0] if "nli-cross-agent-alignment-all-repeats-no_stance" in aggregate_df.columns else None